### ISSUE TITLE
会出现Incorrect TIMESTAMP value: ''2019-07-30''问题，不知道该怎么解决。

### ISSUE THREAD

**Issue by YanRuYu123** [bluemapleman/NewsRecommendSystem#23]
com.jfinal.plugin.activerecord.ActiveRecordException: java.sql.SQLException: Incorrect TIMESTAMP value: ''2019-07-30''
	at com.jfinal.plugin.activerecord.Model.find(Model.java:579)
	at top.qianxinyao.algorithms.RecommendKit.filterReccedNews(RecommendKit.java:124)
	at top.qianxinyao.contentbasedrecommend.ContentBasedRecommender.recommend(ContentBasedRecommender.java:95)
	at top.qianxinyao.Main.JobSetter.executeInstantJob(JobSetter.java:112)
	at top.qianxinyao.Main.JobSetter.executeInstantJobForCertainUsers(JobSetter.java:125)
	at top.qianxinyao.Main.TestDataRunner.runTestData(TestDataRunner.java:37)
	at top.qianxinyao.Main.Main.main(Main.java:26)
Caused by: java.sql.SQLException: Incorrect TIMESTAMP value: ''2019-07-30''
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:379)
	at com.jfinal.plugin.activerecord.Model.find(Model.java:560)
	at com.jfinal.plugin.activerecord.Model.find(Model.java:577)
	... 6 more

**Comment by hhyyssnn** [comment]
请问解决了吗？我也出现了这个问题
