### ISSUE TITLE
我使用的是jdk1.8   在运行时出现类型转换异常java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by 1604051738** [bluemapleman/NewsRecommendSystem#32]
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at com.jfinal.plugin.activerecord.Model.getInt(Model.java:203)
	at top.qianxinyao.hotrecommend.HotRecommender.recommend(HotRecommender.java:50)
	at top.qianxinyao.Main.JobSetter.executeInstantJob(JobSetter.java:114)
	at top.qianxinyao.Main.JobSetter.executeInstantJobForCertainUsers(JobSetter.java:125)
	at top.qianxinyao.Main.Main.main(Main.java:40)
Thu May 21 15:17:30 CST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at com.jfinal.plugin.activerecord.Model.getInt(Model.java:203)
	at top.qianxinyao.hotrecommend.HotRecommender.recommend(HotRecommender.java:50)
	at top.qianxinyao.Main.JobSetter.executeInstantJob(JobSetter.java:114)
	at top.qianxinyao.Main.JobSetter.executeInstantJobForCertainUsers(JobSetter.java:125)
	at top.qianxinyao.Main.Main.main(Main.java:40)
Thu May 21 15:17:30 CST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at com.jfinal.plugin.activerecord.Model.getInt(Model.java:203)
	at top.qianxinyao.hotrecommend.HotRecommender.recommend(HotRecommender.java:50)
	at top.qianxinyao.Main.JobSetter.executeInstantJob(JobSetter.java:114)
	at top.qianxinyao.Main.JobSetter.executeInstantJobForCertainUsers(JobSetter.java:125)
	at top.qianxinyao.Main.Main.main(Main.java:40)
HR has contributed 0 recommending news on average
HR end at Thu May 21 15:17:30 CST 2020
本次推荐结束于Thu May 21 15:17:30 CST 2020

**Comment by 1604051738** [comment]
已解决

**Comment by De-Bufrosa** [comment]
> 
> 
> 已解决

你咋解决的

**Comment by sefei-hao** [comment]
求解决方法

**Comment by Elton123456** [comment]
遇到了同样的问题，升级pom.xml文件中的jfinal版本可以解决
